### ISSUE TITLE
Projectiles don't render anymore

### ISSUE THREAD

**Issue by KayaDLX** [AmperSoftware/TF-Source-2#67] opened 2023-01-29 20:54 UTC
### Describe the bug

Whenever you fire a projectile type weapon, the projectiles do not draw at all.

### To Reproduce

1. Play Medic, Demoman or Soldier
2. Fire your weapon
3. Notice them missing

### Expected behavior

Should draw as expected, this probably broke during recent pain days.

**Comment by yourbadandimbest** [comment] 2023-01-30 10:25
I found the cause and am working on it

**Comment by yourbadandimbest** [comment] 2023-02-02 09:35
Should be fixed in the latest version

**Closed** 2023-02-04 10:59 UTC
Labels: bug
