### ISSUE TITLE
Demomans sticky launcher sometimes keeps playing the sound to launch the sticky when not holding down left click on a server you joined

### ISSUE THREAD

**Issue by Poganator** [AmperSoftware/TF-Source-2#200] opened 2023-08-14 00:21 UTC
### Describe the bug

When using the demo's sticky launcher and not holding left click, the sound keeps playing as if you're holding down left click.

### To Reproduce

To reproduce (tried it on my own hosted game and could not reproduce, but when joining someone else's game, I can reproduce it)

1. Hold down left click with the sticky launcher until it launches the sticky bomb
2. Left click with the sticky launcher and the sound should keep playing

### Expected behavior

When left clicking, the sound should stop and not continue to play

### Media/Files

https://github.com/AmperSoftware/TF-Source-2/assets/37046709/19e7f2b4-5d14-44a8-a93b-933bd6bf7302

**Comment by badandbest** [comment] 2023-08-14 06:05
Yeah this has been a problem for some time and was already reported twice actually https://github.com/AmperSoftware/TF-Source-2/issues/123 https://github.com/AmperSoftware/TF-Source-2/issues/159
I believe there's been attempts to fix this. ( To no avail )

**Comment by Retr0-01** [comment] 2023-08-16 06:38
Duplicate of #123, closing.

**Closed by Retr0-01** 2023-08-16 06:38 UTC
Labels: bug
