### ISSUE TITLE
Weapons not showing up

### ISSUE THREAD

**Issue by Tryak03** [AmperSoftware/TF-Source-2#120] opened 2023-05-17 08:37 UTC
### Describe the bug

When you spawn as any class, you won't be holding a weapon, you won't be able to fire or switch to any other weapon.

### To Reproduce

1. Launch TFS2
2. Pick any class
3. Observe as your character isn't holding anything

### Expected behavior

You should be able to use all of your weapons and see them

### Additional context

badandbest says "There's an exception when regenerating weapons"

**Comment by KayaDLX** [comment] 2023-05-21 16:01
I can't reproduce this issue

**Comment by badandbest** [comment] 2023-05-21 16:03
Because it already got fixed in 125f24117992ff71fc9ce6f20fd35ea517a789a9

**Closed** 2023-05-21 16:04 UTC
Labels: bug
