### ISSUE TITLE
Charge-up sound for stickybomb launcher plays in full whenever you shoot it.

### ISSUE THREAD

**Issue by Yubbin** [AmperSoftware/TF-Source-2#159] opened 2023-06-04 20:22 UTC
### Describe the bug

Whenever I shoot the stickybomb launcher, it makes the charge up sound as if i was holding left-click, even though I am not

### To Reproduce

select stickybomb launcher, quickly left click and do not hold. if you hold left click it seems to fix itself

### Expected behavior

the sound should stop playing when I let go of left click

**Comment by Retr0-01** [comment] 2023-08-16 06:38
Duplicate of #123, closing.

**Closed by Retr0-01** 2023-08-16 06:38 UTC
Labels: bug
